
//! Autogenerated weights for pallet_dao_bounties
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `macbook-pro.lan`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/societal-node
// benchmark
// pallet
// --chain
// dev
// --steps
// 50
// --repeat
// 20
// --pallet
// pallet_dao_bounties
// --extrinsic
// *
// --execution
// wasm
// --wasm-execution
// compiled
// --template
// ./.maintain/frame-weight-template.hbs
// --output
// ./pallets/dao-bounties/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_dao_bounties.
pub trait WeightInfo {
	fn create_bounty() -> Weight;
	fn propose_curator() -> Weight;
	fn unassign_curator() -> Weight;
	fn accept_curator() -> Weight;
	fn award_bounty() -> Weight;
	fn claim_bounty() -> Weight;
	fn close_bounty_active() -> Weight;
	fn extend_bounty_expiry() -> Weight;
	fn spend_funds(b: u32, ) -> Weight;
}

/// Weights for pallet_dao_bounties using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyCount (r:1 w:1)
	/// Proof: DaoBounties BountyCount (max_values: None, max_size: Some(16), added: 2491, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyApprovals (r:1 w:1)
	/// Proof: DaoBounties BountyApprovals (max_values: None, max_size: Some(414), added: 2889, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyDescriptions (r:0 w:1)
	/// Proof: DaoBounties BountyDescriptions (max_values: None, max_size: Some(126), added: 2601, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:0 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn create_bounty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460`
		//  Estimated: `14578`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(30_000_000, 14578)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn propose_curator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `557`
		//  Estimated: `7248`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 7248)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn unassign_curator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `553`
		//  Estimated: `7216`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(27_000_000, 7216)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn accept_curator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `764`
		//  Estimated: `10841`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(31_000_000, 10841)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn award_bounty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `594`
		//  Estimated: `7248`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(19_000_000, 7248)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyDescriptions (r:0 w:1)
	/// Proof: DaoBounties BountyDescriptions (max_values: None, max_size: Some(126), added: 2601, mode: MaxEncodedLen)
	fn claim_bounty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `777`
		//  Estimated: `12422`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(66_000_000, 12422)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyDescriptions (r:0 w:1)
	/// Proof: DaoBounties BountyDescriptions (max_values: None, max_size: Some(126), added: 2601, mode: MaxEncodedLen)
	fn close_bounty_active() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1010`
		//  Estimated: `16047`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(49_000_000, 16047)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn extend_bounty_expiry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `594`
		//  Estimated: `7248`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(18_000_000, 7248)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: DaoBounties BountyApprovals (r:1 w:1)
	/// Proof: DaoBounties BountyApprovals (max_values: None, max_size: Some(414), added: 2889, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:100 w:100)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:100 w:100)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `b` is `[0, 100]`.
	fn spend_funds(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45 + b * (145 ±0)`
		//  Estimated: `5859 + b * (5236 ±0)`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 5859)
			// Standard Error: 531_412
			.saturating_add(Weight::from_parts(27_979_052, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 5236).saturating_mul(b.into()))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyCount (r:1 w:1)
	/// Proof: DaoBounties BountyCount (max_values: None, max_size: Some(16), added: 2491, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyApprovals (r:1 w:1)
	/// Proof: DaoBounties BountyApprovals (max_values: None, max_size: Some(414), added: 2889, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyDescriptions (r:0 w:1)
	/// Proof: DaoBounties BountyDescriptions (max_values: None, max_size: Some(126), added: 2601, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:0 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn create_bounty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460`
		//  Estimated: `14578`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(30_000_000, 14578)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn propose_curator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `557`
		//  Estimated: `7248`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 7248)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn unassign_curator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `553`
		//  Estimated: `7216`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(27_000_000, 7216)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn accept_curator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `764`
		//  Estimated: `10841`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(31_000_000, 10841)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn award_bounty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `594`
		//  Estimated: `7248`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(19_000_000, 7248)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyDescriptions (r:0 w:1)
	/// Proof: DaoBounties BountyDescriptions (max_values: None, max_size: Some(126), added: 2601, mode: MaxEncodedLen)
	fn claim_bounty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `777`
		//  Estimated: `12422`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(66_000_000, 12422)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: DaoBounties BountyDescriptions (r:0 w:1)
	/// Proof: DaoBounties BountyDescriptions (max_values: None, max_size: Some(126), added: 2601, mode: MaxEncodedLen)
	fn close_bounty_active() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1010`
		//  Estimated: `16047`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(49_000_000, 16047)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Dao Policies (r:1 w:0)
	/// Proof: Dao Policies (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:1 w:1)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn extend_bounty_expiry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `594`
		//  Estimated: `7248`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(18_000_000, 7248)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: DaoBounties BountyApprovals (r:1 w:1)
	/// Proof: DaoBounties BountyApprovals (max_values: None, max_size: Some(414), added: 2889, mode: MaxEncodedLen)
	/// Storage: DaoBounties Bounties (r:100 w:100)
	/// Proof: DaoBounties Bounties (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: System Account (r:100 w:100)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `b` is `[0, 100]`.
	fn spend_funds(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45 + b * (145 ±0)`
		//  Estimated: `5859 + b * (5236 ±0)`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 5859)
			// Standard Error: 531_412
			.saturating_add(Weight::from_parts(27_979_052, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 5236).saturating_mul(b.into()))
	}
}
